name: Build aarch64-linux VM image
on:
  push:
jobs:
  build:
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v27
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - run: nix build .#packages.aarch64-linux.vm-image
      - uses: actions/upload-artifact@v4
        with:
          name: builder.qcow2
          path: result
